name: Paper-Test-Plugin
version: ${version}
main: world.kitpvp.slime.test.TestPlugin
description: Paper Test Plugin
author: PaperMC
api-version: ${apiversion}
load: STARTUP
#bootstrapper: io.papermc.testplugin.TestPluginBootstrap
#loader: io.papermc.testplugin.TestPluginLoader
defaultPerm: FALSE
permissions:
#dependencies: